### ISSUE TITLE
ERROR No svg with name 'xxxx' has been loaded with Angular SSR

### ISSUE THREAD

**Issue by RRGT19** [pjlamb12/angular-svg-icon-preloader#8]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm using the [angular-svg-icon-preloader](https://github.com/pjlamb12/angular-svg-icon-preloader) to load my icons.
I have read and followed the "[Usage with Angular Universal](https://github.com/czeckd/angular-svg-icon#usage-with-angular-universal)" to make it work with SSR. I followed and copy the implementation on the [demo-universal-angular-svg-loader](https://github.com/edulelis/demo-universal-angular-svg-loader). It's working and the icons are showing up, but, when my server starts to receive requests, I get these errors in the console:

```
An error occurred loading the icons:
 NetworkError
    at XMLHttpRequest.send (/webapp/dist/web-app/server/main.js:102530:19)
    at Observable._subscribe (/webapp/dist/web-app/server/main.js:188462:17)
No icons will be loaded.

ERROR No svg with name 'xxxxx' has been loaded
```

Maybe there is an issue with the [angular-svg-icon-preloader](https://github.com/pjlamb12/angular-svg-icon-preloader) and SSR?

When I open my App using SSR, I see these requests:
![Image](https://i.ibb.co/LrRt8CR/Screen-Shot-2021-07-23-at-2-16-00-PM.png)

Notice that there is one request to load my icons.json file and then, all my .svg files. This is normal? I don't know what is the cause of my errors in console.

## Expected behavior

While running Angular with SSR, no error messages should appear in the terminal.

## Minimal reproduction of the problem with instructions

Don't have one now. Just create a new angular app with SSR, install both libraries and try to run it on a server or locally. You will see the errors in the logs.

## Environment

Angular CLI: 11.2.10
OS: darwin x64
Angular: 11.2.11
Ivy Workspace: Yes
 
For Tooling issues:
- Node version: Node: 14.15.5
- Platform:  Mac

## Others:
How the icon preloader works with SSR? What we can do to handle it properly and avoid the errors?

**Comment by kuncevic** [comment]
It seems not designed to work with SSR, you had to load the icons from the file system in that case to make universal happy. See [this](https://github.com/edulelis/demo-universal-angular-svg-loader/blob/master/src/app/utils/svg-server.loader.ts#L26)

**Comment by kuncevic** [comment]
It seems not designed to work with SSR, you had to load the icons content from json on the file system when running universal to make universal happy. See [this](https://github.com/edulelis/demo-universal-angular-svg-loader/blob/master/src/app/utils/svg-server.loader.ts#L26)

**Comment by kuncevic** [comment]
It seems not designed to work with SSR, you had to load the icons content from json file using 'fs.readFileSync(...)' when running universal to make universal happy. See [this](https://github.com/edulelis/demo-universal-angular-svg-loader/blob/master/src/app/utils/svg-server.loader.ts#L26)

**Comment by pjlamb12** [comment]
I don't know what the issue might be with SSR apps. It seems like it should work, as all this does is load an svg file and register the icons with angular-svg-icon. I don't have much experience with SSR though.
